### PR TITLE
Add servicebuilder blade tools template

### PR DESCRIPTION
**Pull request by jrao**
Add servicebuilder blade tools template; creates a project containing three modules using a multi-project Gradle build configuration; takes project name argument and a package path argument; the package path argument specifies the root package in which service builder classes are to be generated; use existing _package_ substitution instead of creating a new one

### CODE REVIEW

**Comment by jrao** [comment]
@gamerson FYI, When you create a new servicebuilder project and run buildService, the following method is generated in the API module's FooLocalServiceWrapper class:

	@Override
	public com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		return _fooLocalService.getIndexableActionableDynamicQuery();
	}

This creates a compilation error since com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery is not on the classpath. I didn't run into this issue yesterday so I'm assuming it's due to a recent service builder module update. I checked the blade.servicebuilder.svc project and running buildService there produces the same error.

**Comment by gamerson** [comment]
@jrao  can you open a issue for that and @AndyWu2015  can take a look.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! See 8a849ba...b8bb3af <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Thanks @jrao for the contribution.  I hope more is to come! :)

**Comment by jrao** [comment]
Created https://github.com/gamerson/liferay-blade-tools/issues/17. Looking forward to making more contributions!

**Comment by AndyWu2015** [comment]
Hi @jrao why there is no src/main/java and src/main/resources folder in svc and api project ?

**Comment by jrao** [comment]
@AndyWu2015 Hi Andy, a src/main/java gets generated in the api project when you run gradle buildService. Similarly, src/main/java and a src/main/resources folders get generated in the svc project. I thought it's simplest to let service builder create the folders.

**Comment by AndyWu2015** [comment]
have tried it 。Yes , this is simple . @jrao

**Pull request closed without merging**
