### PR TITLE
Add UUID field for Problem

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
Hey Greg, I only found the version error problem in my local env. please let me know if you have other problem.

**Comment by gamerson** [comment]
This will break usage in IDE.  Can you either add a new constructor that will keep backwards compatibility or send a pull request that fixes this in IDE usage.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-tools/pull/180. [See changes here.](https://github.com/gamerson/liferay-blade-tools/compare/f500c89~2...f500c89) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
