### PR TITLE
change Bundle-SymbolicName to _name_

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by AndyWu2015** [comment]
Oh I see , I need update test classes also

**Comment by gamerson** [comment]
Please resend, thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Yeah can you send test updates?  thanks!

On Thu, Jan 28, 2016 at 11:09 PM, Andy Wu <notifications@github.com> wrote:

> Oh I see , I need update test classes also
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-blade-tools/pull/104#issuecomment-176578606>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Pull request closed without merging**
