### PR TITLE
migrate a theme from plugins sdk to themes

### PR DESCRIPTION
**Pull request by david-truong**
I couldn't ever get it to exit properly... It seems to be migrating properly though...

### CODE REVIEW

**Comment by gamerson** [comment]
@david-truong test failures?

**Comment by david-truong** [comment]
Not locally but I think it's cause a new workspace plugin got checked in

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-tools/pull/90. [See changes here.](https://github.com/gamerson/liferay-blade-tools/compare/6ffe963~3...6ffe963) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
